"""empty message

Revision ID: eb43c548c0ff
Revises: 8647c214f7c7
Create Date: 2025-03-27 05:50:59.144894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb43c548c0ff'
down_revision = '8647c214f7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tectonic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tectonic', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
